### ISSUE TITLE
Acces sfaira ontologies 

### ISSUE THREAD

**Issue by Hrovatin** [theislab/sfaira#101]
I would like access Sfaira ontologies and synonym matching functionalities in my Python code for genes and for cell types. 
I want to write functions that would take as input cell type name OR gene name + organism and return whether this is a valid name and possibly suggest what a correct name would be. Currently the priority is only to check if gene name is a valid gene names for organism and if cell type is a valid Cell Ontology cell type. 

David linked me https://github.com/theislab/sfaira/blob/3d89f688d9a91704fce49aa7648e8359eac21f0c/sfaira/versions/metadata/base.py#L737 . Does this work by only fuzzy string matching (e.g. could match "Beta"  to "beta cells" - different case/substring) or does it use all synonyms that can be extracted from Cell Ontology database download file (e.g. could match"beta" to "pancreatic B cell" - completely different words).

Also, please let me know if this can be done with current version of Sfaira or it would take a while to implement.

**Comment by davidsebfischer** [comment]
Good idea! Let's explicitly define an interface for this, how about this?

```python
def map_celltype_to_ontology(
            source: str,
            match_only: bool = False,
            include_synonyms: bool = True,
            anatomical_constraint: Union[str, None] = None,
            n_suggest: int = 10,
    ) -> List[str]:
        """
        Map free text node name to ontology node names via fuzzy string matching.

        :param source: Free text node label which is to be matched to ontology nodes.
        :param match_only: Whether to include strict matches only in output.
        :param include_synonyms: Whether to include synonyms of nodes in string search.
        :param anatomical_constraint: Whether to require suggestions to be within a target anatomy defined within UBERON.
        :param n_suggest: Number of cell types to suggest.
        :return: List of high priority matches.
        """
```
This interface could be exposed essentially immidiately as it is very close to what we are already using internally.

> Does this work by only fuzzy string matching (e.g. could match "Beta" to "beta cells" - different case/substring) or does it use all synonyms that can be extracted from Cell Ontology database download file (e.g. could match"beta" to "pancreatic B cell" - completely different words).

It does a lot of things internally, for the exact recipe you would have to look at the code (we are also interested in optimising this recipe if you find it not working well), in brief:

- synonyms (such as "beta cell" and "pancreatic type B cell") are considered if `include_synonyms==True`, these synonyms are usually annotated in the cell ontology. So finding "pancreatic type B cell" from "beta" in a pancreas sample is not an issue.
- we use anatomic information also, this is annotated in the doc string

**Comment by Hrovatin** [comment]
This sounds great. So if I wanted to check if cell name was valid and if not return synonyms I would call something like
```
map_celltype_to_ontology(
            source=cell_name,
            match_only = False,
            include_synonyms= True,
            anatomical_constraint= None,
            n_suggest: int = 10)
```
Which would return a list of possible names from ontology. Then I would check if the source I used as input is in the returned list. -> In this case it is a valid ontology name. If source is not in returned list it is not valid and I would output list with suggestions.

**Comment by davidsebfischer** [comment]
Ok, we can add an additional parameter that lead to the string itself being returned if it is in the ontology. This is not always desired though so I would be careful with that: "stellate cell" is a valid term but in the context of a pancreas sample you might be able to narrow this down to a much more specific term, e.g. "pancreatic stellate cell", so if anatomic information is available I essentially never rely on perfect matches in my workflows.

**Comment by Hrovatin** [comment]
Thanks for letting me know. Then I will also just use what your function returns (the list) followed by manual curation.

**Comment by davidsebfischer** [comment]
@Hrovatin this is available in dev now under `sfaira.data.utils`, usage is documented in the docstring.

**Comment by Hrovatin** [comment]
There are a few problems with the function, see below:
```
map_celltype_to_ontology('beta','mouse')
/Users/karin.hrovatin/Documents/GitHub/sfaira/sfaira/versions/metadata/base.py:204: UserWarning: DAG was broken
  warnings.warn("DAG was broken")
[['activated CD8-positive, alpha-beta T cell, human', 'CD8-positive, CD28-negative, alpha-beta regulatory T cell', 'effector memory CD8-positive, alpha-beta T cell, terminally differentiated', 'basophil cell of pars distalis of adenohypophysis']]

map_celltype_to_ontology('beta cell','mouse')
/Users/karin.hrovatin/Documents/GitHub/sfaira/sfaira/versions/metadata/base.py:204: UserWarning: DAG was broken
  warnings.warn("DAG was broken")
[['cell', 'type B pancreatic cell', 'basophil cell of pars distalis of adenohypophysis', 'jejunal goblet cell']]

```
1.) We would prefer not to have cell types separated by organism. I also do not see online on Cell Ontology cell types being associated with only specific organisms. So where does the need for organism come from and what does it do?
2.) The fuzzy string mapping could be improved. If I input "beta" I do not get back official name 'type B pancreatic cell' - this is also problem online on cell ontology where with this search the 'type B pancreatic cell' is not among top hits. However, if I input "beta cell"  I get 'type B pancreatic cell', which is also high in online search. It seems odd that I get so different results based on whether I add "cell" or not.

**Comment by Hrovatin** [comment]
Also, anatomical constraint does not work:
```
map_celltype_to_ontology('T','mouse',anatomical_constraint='blood')
/Users/karin.hrovatin/Documents/GitHub/sfaira/sfaira/versions/metadata/base.py:204: UserWarning: DAG was broken
  warnings.warn("DAG was broken")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/karin.hrovatin/Documents/GitHub/sfaira/sfaira/data/utils.py", line 38, in map_celltype_to_ontology
    matches = cu.prepare_celltype_map_fuzzy(
  File "/Users/karin.hrovatin/Documents/GitHub/sfaira/sfaira/versions/metadata/base.py", line 902, in prepare_celltype_map_fuzzy
    matchesi = matchesi.update({"anatomic_string_match": [
AttributeError: 'NoneType' object has no attribute 'update'

**Comment by Hrovatin** [comment]
It also takes a while to run. So if checking multiple cell types would there be an easy way to remove redundant steps and speed it up - e.g. is there an object initialization step that takes a while or something similar?

**Comment by Hrovatin** [comment]
Also, if i input perfect match I never get a list of suggestions desipte choices_for_perfect_match.
```
map_celltype_to_ontology(source='T cell',
...                                            organism='mouse',
...                                            include_synonyms=True,
...                                            anatomical_constraint=anatomical_constraint,
...                                            n_suggest=5,
...                                            choices_for_perfect_match=True,
...                                            keep_strategy=False
...                                            )
/Users/karin.hrovatin/Documents/GitHub/sfaira/sfaira/versions/metadata/base.py:204: UserWarning: DAG was broken
  warnings.warn("DAG was broken")
['T cell']
map_celltype_to_ontology(source='T cell',
...                                            organism='mouse',
...                                            include_synonyms=True,
...                                            anatomical_constraint=anatomical_constraint,
...                                            n_suggest=5,
...                                            choices_for_perfect_match=False,
...                                            keep_strategy=False
...                                            )
/Users/karin.hrovatin/Documents/GitHub/sfaira/sfaira/versions/metadata/base.py:204: UserWarning: DAG was broken
  warnings.warn("DAG was broken")
'T cell'

**Comment by davidsebfischer** [comment]
Thanks for all the feedback!

> 1.) We would prefer not to have cell types separated by organism. I also do not see online on Cell Ontology cell types being associated with only specific organisms. So where does the need for organism come from and what does it do? Also, I inputed organism mouse and got a resulting celltype that contains 'human'.

CO is not organism specific, it seems that in this case, they added a node which they believe to only occur in humans, which is why they might have labeled it this way. Here we would need to look into the T cell CO tree, happy to do that. Inputting mouse would not change that because the node in CO does not have an organism label. We could however counterselect nodes which have these human suffixes, this might be unsafe before we know exactly why they gave it this suffix though.

> 2.) The fuzzy string mapping could be improved. If I input "beta" I do not get back official name 'type B pancreatic cell' - this is also problem online on cell ontology where with this search the 'type B pancreatic cell' is not among top hits. However, if I input "beta cell" I get 'type B pancreatic cell', which is also high in online search. It seems odd that I get so different results based on whether I add "cell" or not.

"beta cell" is an exact synonym, this is why it s easy to find, the matches that you  are seeing come from different match strategies to cover as many possibilities as possible. I think you ll find the correct cell if you input beta and constraint by pancreas? We could check for a string matching that gives higher scores if the full string is not much longer than the query, this should penalize the hits you are seeing now.

> 3.) There is a warning.

This is from UBERON, this does not effect your query.

> Also, anatomical constraint does not work:

Sorry I fixed this on another branch and did not merge, it is merged into `dev` now in #104

> It also takes a while to run. So if checking multiple cell types would there be an easy way to remove redundant steps and speed it up - e.g. is there an object initialization step that takes a while or something similar?

Yes we could accept lists as input, most of the time is required for loading the ontology which is happening repeatedly if you call once for each cell type.

> Also, if i input perfect match I never get a list of suggestions desipte choices_for_perfect_match.

I'm addressing this right now.

**Comment by davidsebfischer** [comment]
> Also, if i input perfect match I never get a list of suggestions desipte choices_for_perfect_match.

I addressed this in #110, you can try it again now, it should work better, see also the additional arguments now!

**Comment by Hrovatin** [comment]
Hi, thanks for correcting the code. However, this still does not work (it works if I use 'beta' or ['beta'] as query):
```
map_celltype_to_ontology(queries=['beta','alpha'],
                                          organism='mouse',
                                          include_synonyms=True,
                                          anatomical_constraint='pancreas',
                                          n_suggest=5,
                                          choices_for_perfect_match=True,
                                          keep_strategy=False,
                                          always_return_list=True
                                           )
/Users/karin.hrovatin/Documents/GitHub/sfaira/sfaira/versions/metadata/base.py:204: UserWarning: DAG was broken
  warnings.warn("DAG was broken")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/karin.hrovatin/Documents/GitHub/sfaira/sfaira/data/utils.py", line 66, in map_celltype_to_ontology
    if len(matches_i.values()) == 1 and isinstance(list(matches_i.values())[0], str):
AttributeError: 'bool' object has no attribute 'values'

**Comment by davidsebfischer** [comment]
Thanks for the bug report, this was an issue with list input, it s now fixed on dev also part of the unit testing!

**Comment by davidsebfischer** [comment]
@Hrovatin Is this still an issue?

**Comment by Hrovatin** [comment]
Yes, it works now.
